services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: exemplo
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/mysql:/var/lib/mysql
